### ISSUE TITLE
Use 

### ISSUE THREAD

**Issue by alexalburca** [pokiiio/node-red-contrib-web-page-screenshot#3]
Hi

I can't use this module, I need to take a screenshot of a web page and return the image to a telegram bot.

But with this module I can not return can help?

With your example in my environment there is no log return.

**Comment by nygma2004** [comment]
I am also trying to do the same. I think the issue is with the chromium-browser install in raspberry pi. When I trigger the node, I see the following in Node Red Log:

`
(node:491) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
bootstrap_helper: /usr/lib/chromium-browser/nacl_helper: Cannot open ELF file!  errno=2
[1:1:1213/105402.285765:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes)
[4613:4613:1213/105402.293272:ERROR:browser_main_loop.cc(495)] Failed to put Xlib into threaded mode.
[4613:4613:1213/105402.301780:ERROR:browser_main_loop.cc(272)] Gtk: cannot open display:
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
at onClose (/home/pi/.node-red/node_modules/puppeteer/lib/Launcher.js:348:14)
at ChildProcess.helper.addEventListener (/home/pi/.node-red/node_modules/puppeteer/lib/Launcher.js:338:60)
at ChildProcess.emit (events.js:203:15)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
(node:491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
`

I think this is because either it is not installed correctly, or something else. I tried sudo apt-get install chromium-browser in my PI but it says that it is already installed. And the file is definitely there in /usr/bin/chromium-browser.
I am not sure if you know what the issue is with the chromium.

**Comment by pokiiio** [comment]
Chromium which this node includes is for x86 arch.
So, if your arch is not x86, please set a following parameter.

>**executablePath (Optional)**
You can specify chromium/chrome executable with the path. For those who use x86 arch, this can be blank, however, if you use this node on ARM arch (e.g. Raspberry Pi), you have to install headless-mode-available chromium-browser and set the path.
>
>_Fortunately, Raspbian OS (as of ver. April 2019) includes compatible chromium-browser, so just set /usr/bin/chromium-browser to this blank._

**Comment by timdonovanuk** [comment]
Aren't most people these days going to be running Node-Red in a x64 docker container? 

This renders this node completely incompatible, as it's not simple to install depedencies in a container.
